#!/bin/sh
set -eu

PROGBASE=$(d=$(dirname -- "${0}"); cd "${d}" && pwd)
PROGNAME=$(basename -- "${0}")

usage() {
	printf 'usage: %s [-h] version\n' "${PROGNAME}"
}

while getopts h- argv; do
	case "${argv}" in
	h)	usage
		exit 0
		;;
	-)	break
		;;
	*)	usage >&2
		exit 1
		;;
	esac
	shift $(( OPTIND + 1 ))
done

[ X-- != X"${1:-}" ] || shift

if [ 1 -ne $# ]; then
	usage >&2
	exit 1
fi

if [ -t 1 ]; then
	printf 'error: output must be piped to a file\n' >&2
	printf 'mkmeta version. >incus.tar.xz\n' >&2
	exit 1
fi

# -------------------------------------------------------------------- #

tmpdir=$(mktemp -d)
trap "/bin/rm -rf '${tmpdir}'" EXIT INT QUIT TERM

cd "${tmpdir}"

date=$(TZ= date +%s)
sed -e "s|@date@|${date}|" "${PROGBASE}/metas/${1}.in" >metadata.yaml

tar -f- -c metadata.yaml | xz -c9
